# protovalidate/codegen.bzl
"""lean_protovalidate_library: Lean refinement types from protovalidate CEL rules.

Mirrors grpc-lean's lean_proto_library staging: a codegen rule runs protoc with
protoc-gen-lean-protovalidate over a proto_library, then a lean_library
compiles the generated modules against the grpc-lean base types and the
Protovalidate runtime.
"""

load("@rules_lean//lean:defs.bzl", "lean_library")

def _default_module_prefix(name):
    """PascalCase a target name, matching lean_proto_library's default."""
    parts = []
    for raw in name.replace("-", "_").split("_"):
        if raw:
            parts.append(raw[0].upper() + raw[1:])
    return "".join(parts) if parts else "Proto"

def _module_prefix_path(module_prefix):
    return module_prefix.replace(".", "/")

def _proto_output_basename(src):
    if src.basename.endswith(".proto"):
        return src.basename[:-len(".proto")]
    return src.basename

def _proto_import_path(src, proto_source_root):
    """The canonical import path protoc records for a proto source (its path
    relative to the target's proto source root, handling strip_import_prefix
    virtual imports)."""
    if proto_source_root and proto_source_root != ".":
        root = proto_source_root + "/"
        if src.path.startswith(root):
            return src.path[len(root):]
    return src.path

def _proto_path_args(proto_info, proto_sources):
    seen = {}
    paths = []
    for path in proto_info.transitive_proto_path.to_list():
        if path not in seen:
            seen[path] = True
            paths.append(path)
    for src in proto_sources:
        if src.dirname and src.dirname not in seen:
            seen[src.dirname] = True
            paths.append(src.dirname)
    return paths

_LeanProtovalidateGenInfo = provider(
    doc = "Lean sources generated by protoc-gen-lean-protovalidate.",
    fields = {
        "lean_srcs": "Generated Lean source files.",
        "module_prefix": "Lean module prefix used for generated modules.",
        "base_module_prefix": "Module prefix of the grpc-lean base modules for the same protos.",
        "proto_paths": "Proto import paths covered by this target.",
    },
)

def _lean_protovalidate_generate_impl(ctx):
    proto_info = ctx.attr.proto[ProtoInfo]
    proto_sources = proto_info.direct_sources
    if not proto_sources:
        fail("No proto sources found")

    module_prefix = ctx.attr.module_prefix
    if not module_prefix:
        module_prefix = _default_module_prefix(ctx.label.name)
    module_path = _module_prefix_path(module_prefix)

    outputs = []
    copy_lines = []
    for src in proto_sources:
        base = _proto_output_basename(src)
        out = ctx.actions.declare_file(module_path + "/" + base + ".lean")
        outputs.append(out)
        copy_lines.append('mkdir -p "$(dirname \'{out}\')"'.format(out = out.path))
        copy_lines.append('cp "$TMP/{base}.lean" "{out}"'.format(base = base, out = out.path))

    # Cross-target validated references resolve to the dep targets' prefixes.
    dep_module_entries = []
    for dep in ctx.attr.deps:
        info = dep[_LeanProtovalidateGenInfo]
        for path in info.proto_paths:
            dep_module_entries.append(path + "@" + info.base_module_prefix + "@" + info.module_prefix)

    args = ctx.actions.args()
    for path in _proto_path_args(proto_info, proto_sources):
        args.add("--proto_path=" + path)
    args.add("--plugin=protoc-gen-lean-protovalidate=" + ctx.executable._plugin.path)
    args.add("--lean-protovalidate_opt=lean4_prefix={},base_prefix={}".format(
        module_prefix,
        ctx.attr.base_module_prefix,
    ))
    if dep_module_entries:
        args.add("--lean-protovalidate_opt=dep_modules=" + ";".join(dep_module_entries))
    args.add_all([src.path for src in proto_sources])

    command = """set -eu
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
"{protoc}" --lean-protovalidate_out="$TMP" "$@"
{copy_outputs}
""".format(
        protoc = ctx.executable._protoc.path,
        copy_outputs = "\n".join(copy_lines),
    )

    ctx.actions.run_shell(
        command = command,
        arguments = [args],
        inputs = depset(
            direct = list(proto_sources),
            transitive = [proto_info.transitive_sources],
        ),
        outputs = outputs,
        tools = [
            ctx.executable._protoc,
            ctx.executable._plugin,
        ],
        mnemonic = "ProtoGenLeanProtovalidate",
        progress_message = "Generating Lean protovalidate refinements for %s" % ctx.label,
    )

    return [
        DefaultInfo(files = depset(outputs)),
        OutputGroupInfo(lean_srcs = depset(outputs)),
        _LeanProtovalidateGenInfo(
            lean_srcs = depset(outputs),
            module_prefix = module_prefix,
            base_module_prefix = ctx.attr.base_module_prefix,
            proto_paths = [
                _proto_import_path(src, proto_info.proto_source_root)
                for src in proto_sources
            ],
        ),
    ]

_lean_protovalidate_generate = rule(
    implementation = _lean_protovalidate_generate_impl,
    doc = "Generates Lean refinement modules from protovalidate CEL annotations.",
    attrs = {
        "proto": attr.label(
            doc = "The proto_library target to generate refinements for.",
            mandatory = True,
            providers = [ProtoInfo],
        ),
        "module_prefix": attr.string(
            doc = "Lean module prefix for generated modules. Defaults to PascalCase(name).",
        ),
        "base_module_prefix": attr.string(
            doc = "Module prefix used by the grpc-lean lean_proto_library for the same protos.",
            mandatory = True,
        ),
        "deps": attr.label_list(
            doc = "Codegen targets of other lean_protovalidate_library targets whose protos this target imports.",
            providers = [_LeanProtovalidateGenInfo],
        ),
        "_protoc": attr.label(
            default = "@protobuf//:protoc",
            executable = True,
            cfg = "exec",
        ),
        "_plugin": attr.label(
            default = Label("//cmd/protoc-gen-lean-protovalidate"),
            executable = True,
            cfg = "exec",
        ),
    },
)

def _base_target_name(label):
    name = label.split(":")[-1]
    return name.split("/")[-1]

def _gen_label(label):
    """The <name>_gen codegen target label for a lean_protovalidate_library label."""
    if ":" in label:
        return label + "_gen"
    if "//" in label:
        return label + ":" + label.rsplit("/", 1)[-1] + "_gen"
    return label + "_gen"

def lean_protovalidate_library(
        name,
        proto,
        lean_proto,
        module_prefix = None,
        base_module_prefix = None,
        valid_deps = None,
        deps = None,
        visibility = None,
        **kwargs):
    """Generates and compiles Lean refinement types for protovalidate CEL rules.

    Args:
        name: Target name; also the default source of the module prefix
            (PascalCase(name), e.g. shipping_valid -> ShippingValid.shipping).
        proto: proto_library with the annotated protos (its deps must include
            protovalidate's validate_proto).
        lean_proto: the grpc-lean lean_proto_library for the same protos; the
            generated refinements import and wrap its types.
        module_prefix: override the Lean module prefix.
        base_module_prefix: module prefix of lean_proto's generated modules;
            defaults to PascalCase(lean_proto target name), matching
            lean_proto_library's own default. Pass explicitly if the base set
            a custom module_prefix.
        valid_deps: other lean_protovalidate_library targets whose protos this
            target's protos import; generated cross-target validated
            references resolve to those targets' module prefixes.
        deps: extra Lean deps for the compiled library.
        visibility: standard visibility.
        **kwargs: forwarded to the underlying lean_library.
    """
    if not base_module_prefix:
        base_module_prefix = _default_module_prefix(_base_target_name(lean_proto))

    gen_name = name + "_gen"
    _lean_protovalidate_generate(
        name = gen_name,
        proto = proto,
        # Resolve the default here so it derives from the user-facing target
        # name, not the internal "<name>_gen" codegen target.
        module_prefix = module_prefix or _default_module_prefix(name),
        base_module_prefix = base_module_prefix,
        deps = [_gen_label(d) for d in (valid_deps or [])],
        # Same visibility as the library so downstream valid_deps can read
        # this target's provider across packages.
        visibility = visibility,
    )

    srcs_name = name + "_srcs"
    native.filegroup(
        name = srcs_name,
        srcs = [":" + gen_name],
        output_group = "lean_srcs",
        visibility = ["//visibility:private"],
    )

    lean_deps = [
        lean_proto,
        Label("//lean:protovalidate_cel"),
        Label("//lean:protovalidate_runtime"),
    ]
    if valid_deps:
        lean_deps = lean_deps + valid_deps
    if deps:
        lean_deps = lean_deps + deps

    lean_library(
        name = name,
        srcs = [":" + srcs_name],
        strip_module_prefix = native.package_name(),
        deps = lean_deps,
        visibility = visibility,
        **kwargs
    )
