// Command formatcorpus maintains and renders the differential battery for
// `Protovalidate.Cel.Format`.
//
// The formats (email, hostname, ip, uri, ...) are hand-written RFC grammars
// with no reference cross-check, so a divergence from protovalidate would be
// silent. The oracle is upstream protovalidate's own conformance suite, whose
// expectations are normative for every protovalidate runtime.
//
// Two modes:
//
//	formatcorpus -extract <protovalidate-src> > Test/format_corpus.tsv
//	    Parse tools/protovalidate-conformance/internal/cases/{cases_is_*.go,
//	    cases_strings.go} and emit every string-format case as a corpus row.
//	    <protovalidate-src> is a checkout of github.com/bufbuild/protovalidate
//	    at the version this module depends on; under bazel it is
//	    $(bazel info output_base)/external/protovalidate+. This mode is run by
//	    hand when refreshing the corpus, never during a build.
//
//	formatcorpus <corpus.tsv>
//	    Render the corpus as a Lean module of `#guard`s (the build's genrule).
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/petersonbill64/protovalidate-lean/celtolean"
)

func main() {
	extract := flag.String("extract", "",
		"path to a bufbuild/protovalidate checkout; extract its conformance "+
			"string-format cases as a corpus TSV instead of rendering Lean")
	namespace := flag.String("namespace", "FormatCorpus", "Lean namespace for the rendered module")
	flag.Parse()

	if *extract != "" {
		if err := runExtract(*extract, os.Stdout); err != nil {
			fmt.Fprintln(os.Stderr, "formatcorpus:", err)
			os.Exit(1)
		}
		return
	}
	if flag.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "usage: formatcorpus [-namespace N] <corpus.tsv>")
		fmt.Fprintln(os.Stderr, "       formatcorpus -extract <protovalidate-src>")
		os.Exit(2)
	}
	f, err := os.Open(flag.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, "formatcorpus:", err)
		os.Exit(1)
	}
	defer f.Close()
	probes, err := celtolean.ParseFormatCorpus(f)
	if err != nil {
		fmt.Fprintln(os.Stderr, "formatcorpus:", err)
		os.Exit(1)
	}
	if err := render(os.Stdout, *namespace, probes); err != nil {
		fmt.Fprintln(os.Stderr, "formatcorpus:", err)
		os.Exit(1)
	}
}

// -- rendering -------------------------------------------------------------

func render(w *os.File, namespace string, probes []celtolean.FormatProbe) error {
	p := func(args ...string) { fmt.Fprintln(w, strings.Join(args, "")) }
	p("-- Generated by cmd/formatcorpus from Test/format_corpus.tsv. DO NOT EDIT.")
	p("module")
	p()
	// `#guard` evaluates its argument while elaborating the module, so the
	// implementations must be visible in the meta context too.
	p("public meta import Protovalidate.Cel")
	p()
	p("/-!")
	p("Differential battery for `Protovalidate.Cel.Format`.")
	p()
	p("Every guard below is one case of upstream protovalidate's conformance suite:")
	p("the input, and the answer protovalidate requires of any conforming runtime.")
	p("Lean re-decides each at elaboration time, so a disagreement between")
	p("`Cel.Format` and protovalidate on an extracted case fails the build.")
	p()
	p("Finitely many points: this is differential testing against a fixed corpus,")
	p("not a proof that `Cel.Format` implements the RFCs or agrees with")
	p("protovalidate on inputs the corpus does not contain.")
	p("-/")
	p()
	p("public section")
	p()
	p("namespace ", namespace)
	p()

	byFormat := map[string][]celtolean.FormatProbe{}
	for _, pr := range probes {
		byFormat[pr.Format] = append(byFormat[pr.Format], pr)
	}
	formats := make([]string, 0, len(byFormat))
	for f := range byFormat {
		formats = append(formats, f)
	}
	sort.Strings(formats)
	for _, f := range formats {
		rows := byFormat[f]
		accepted := 0
		for _, r := range rows {
			if r.Accept {
				accepted++
			}
		}
		p("/-! ### ", f, " — ", strconv.Itoa(len(rows)), " cases (",
			strconv.Itoa(accepted), " accepted, ", strconv.Itoa(len(rows)-accepted), " rejected) -/")
		for _, r := range rows {
			guard, err := celtolean.FormatProbeGuard(r)
			if err != nil {
				return err
			}
			p(guard, "  -- ", r.Case)
		}
		p()
	}
	p("end ", namespace)
	return nil
}

// -- extraction ------------------------------------------------------------

// caseFiles are the conformance suites covering the string formats.
var caseFiles = []string{
	"cases_is_email.go",
	"cases_is_host_and_port.go",
	"cases_is_hostname.go",
	"cases_is_ip.go",
	"cases_is_ip_prefix.go",
	"cases_is_uri.go",
	"cases_is_uri_ref.go",
	"cases_strings.go",
}

const casesDir = "tools/protovalidate-conformance/internal/cases"

// msgSpec maps one conformance message type to the format predicate its CEL
// rule applies, plus the rule id that must be the one violated (so a case
// failing for an unrelated reason is not mistaken for a format answer).
type msgSpec struct {
	// format derives the corpus format key from the message's set fields.
	format func(fields map[string]string) (string, error)
	// rulePrefix is the rule id prefix expected in a Violations result.
	rulePrefix string
}

func fixed(key, rulePrefix string) msgSpec {
	return msgSpec{
		format:     func(map[string]string) (string, error) { return key, nil },
		rulePrefix: rulePrefix,
	}
}

// specs covers the conformance messages whose sole rule is a string-format
// predicate. `Not*` variants are deliberately absent: `string.<format> =
// false` disables the rule rather than negating it, so those cases carry no
// information about the format.
var specs = map[string]msgSpec{
	// library.proto: the CEL string-format functions, called directly.
	"IsEmail":    fixed("email", "library.is_email"),
	"IsHostname": fixed("hostname", "library.is_hostname"),
	"IsUri":      fixed("uri", "library.is_uri"),
	"IsUriRef":   fixed("uri_ref", "library.is_uri_ref"),
	"IsIp": {
		format: func(f map[string]string) (string, error) {
			if v, ok := f["Version"]; ok {
				return "ip:" + v, nil
			}
			return "ip", nil
		},
		rulePrefix: "library.is_ip",
	},
	"IsIpPrefix": {
		format: func(f map[string]string) (string, error) {
			v, hasV := f["Version"]
			s, hasS := f["Strict"]
			switch {
			case hasV && hasS:
				return "ip_prefix:" + v + ":" + s, nil
			case hasV:
				return "ip_prefix:" + v, nil
			case hasS:
				return "ip_prefix:" + s, nil
			}
			return "ip_prefix", nil
		},
		rulePrefix: "library.is_ip_prefix",
	},
	"IsHostAndPort": {
		format: func(f map[string]string) (string, error) {
			// port_required is a plain bool field; unset means false.
			pr, ok := f["PortRequired"]
			if !ok {
				pr = "false"
			}
			return "host_and_port:" + pr, nil
		},
		rulePrefix: "library.is_host_and_port",
	},

	// strings.proto: the standard `string.<format>` rules, which lower onto
	// the same predicates.
	"StringEmail":               fixed("email", "string.email"),
	"StringHostname":            fixed("hostname", "string.hostname"),
	"StringAddress":             fixed("address", "string.address"),
	"StringURI":                 fixed("uri", "string.uri"),
	"StringURIRef":              fixed("uri_ref", "string.uri_ref"),
	"StringIP":                  fixed("ip", "string.ip"),
	"StringIPv4":                fixed("ip:4", "string.ipv4"),
	"StringIPv6":                fixed("ip:6", "string.ipv6"),
	"StringIPWithPrefixLen":     fixed("ip_prefix", "string.ip_with_prefixlen"),
	"StringIPv4WithPrefixLen":   fixed("ip_prefix:4", "string.ipv4_with_prefixlen"),
	"StringIPv6WithPrefixLen":   fixed("ip_prefix:6", "string.ipv6_with_prefixlen"),
	"StringIPPrefix":            fixed("ip_prefix:true", "string.ip_prefix"),
	"StringIPv4Prefix":          fixed("ip_prefix:4:true", "string.ipv4_prefix"),
	"StringIPv6Prefix":          fixed("ip_prefix:6:true", "string.ipv6_prefix"),
	"StringHostAndPort":         fixed("host_and_port:true", "string.host_and_port"),
	"StringHostAndOptionalPort": fixed("host_and_port:false", "string.host_and_port"),
	"StringUUID":                fixed("uuid", "string.uuid"),
	"StringTUUID":               fixed("tuuid", "string.tuuid"),
}

func runExtract(src string, w *os.File) error {
	dir := filepath.Join(src, casesDir)
	var probes []celtolean.FormatProbe
	skipped := map[string]int{}
	for _, name := range caseFiles {
		path := filepath.Join(dir, name)
		got, skip, err := extractFile(path)
		if err != nil {
			return err
		}
		probes = append(probes, got...)
		for k, v := range skip {
			skipped[k] += v
		}
	}

	// Deduplicate; the same input often appears in both the library and the
	// standard-rule suite. A contradiction between two cases means the corpus
	// was misread — fail loudly rather than emit an unsatisfiable guard.
	type key struct{ format, input string }
	seen := map[key]celtolean.FormatProbe{}
	var out []celtolean.FormatProbe
	for _, p := range probes {
		k := key{p.Format, p.Input}
		if prev, ok := seen[k]; ok {
			if prev.Accept != p.Accept {
				return fmt.Errorf("conflicting expectations for %s(%q): %s says %t, %s says %t",
					p.Format, p.Input, prev.Case, prev.Accept, p.Case, p.Accept)
			}
			continue
		}
		seen[k] = p
		out = append(out, p)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Format != out[j].Format {
			return out[i].Format < out[j].Format
		}
		if out[i].Case != out[j].Case {
			return out[i].Case < out[j].Case
		}
		return out[i].Input < out[j].Input
	})

	fmt.Fprintln(w, "# Test/format_corpus.tsv — differential corpus for Protovalidate.Cel.Format.")
	fmt.Fprintln(w, "#")
	fmt.Fprintln(w, "# Extracted by `bazel run //cmd/formatcorpus -- -extract <protovalidate-src>`")
	fmt.Fprintln(w, "# from upstream protovalidate's conformance suite")
	fmt.Fprintf(w, "#   %s/{%s}\n", casesDir, strings.Join(caseFiles, ","))
	fmt.Fprintln(w, "# (the `protovalidate` bazel module this build already depends on). Those")
	fmt.Fprintln(w, "# expectations are normative for every protovalidate runtime, so they are the")
	fmt.Fprintln(w, "# reference this repo's hand-written RFC grammars are differentially tested")
	fmt.Fprintln(w, "# against. DO NOT EDIT BY HAND — re-extract instead.")
	fmt.Fprintln(w, "#")
	fmt.Fprintln(w, "# Columns: format (name[:arg]*, mirroring the CEL call), expected acceptance,")
	fmt.Fprintln(w, "# input (Go-quoted), upstream case name.")
	if err := celtolean.WriteFormatCorpus(w, out); err != nil {
		return err
	}
	names := make([]string, 0, len(skipped))
	for n := range skipped {
		names = append(names, n)
	}
	sort.Strings(names)
	fmt.Fprintf(os.Stderr, "formatcorpus: %d cases extracted (%d after dedup)\n", len(probes), len(out))
	for _, n := range names {
		fmt.Fprintf(os.Stderr, "formatcorpus: skipped %d case(s) of unmapped message %s\n", skipped[n], n)
	}
	return nil
}

func extractFile(path string) ([]celtolean.FormatProbe, map[string]int, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, nil, err
	}
	var out []celtolean.FormatProbe
	skipped := map[string]int{}
	var walkErr error
	ast.Inspect(file, func(n ast.Node) bool {
		cl, ok := n.(*ast.CompositeLit)
		if !ok || !isSelector(cl.Type, "suites", "Suite") {
			return true
		}
		for _, elt := range cl.Elts {
			kv, ok := elt.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			caseName, ok := stringLit(kv.Key)
			if !ok {
				continue
			}
			body, ok := kv.Value.(*ast.CompositeLit)
			if !ok {
				continue
			}
			probe, msgName, err := extractCase(caseName, body)
			if err != nil {
				walkErr = fmt.Errorf("%s: case %q: %w", filepath.Base(path), caseName, err)
				return false
			}
			if probe == nil {
				if msgName != "" {
					skipped[msgName]++
				}
				continue
			}
			out = append(out, *probe)
		}
		return false
	})
	return out, skipped, walkErr
}

// extractCase reads one `{Message: &cases.X{...}, Expected: results.…}` entry.
// It returns (nil, msgName, nil) when the message type is not a string-format
// case.
func extractCase(caseName string, body *ast.CompositeLit) (*celtolean.FormatProbe, string, error) {
	var msg *ast.CompositeLit
	var expected *ast.CallExpr
	for _, elt := range body.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		id, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		switch id.Name {
		case "Message":
			un, ok := kv.Value.(*ast.UnaryExpr)
			if !ok {
				return nil, "", nil
			}
			if msg, ok = un.X.(*ast.CompositeLit); !ok {
				return nil, "", nil
			}
		case "Expected":
			expected, _ = kv.Value.(*ast.CallExpr)
		}
	}
	if msg == nil || expected == nil {
		return nil, "", nil
	}
	sel, ok := msg.Type.(*ast.SelectorExpr)
	if !ok {
		return nil, "", nil
	}
	msgName := sel.Sel.Name
	spec, ok := specs[msgName]
	if !ok {
		return nil, msgName, nil
	}

	fields, err := messageFields(msg)
	if err != nil {
		return nil, msgName, err
	}
	val, ok := fields["Val"]
	if !ok {
		return nil, msgName, fmt.Errorf("no Val field")
	}
	delete(fields, "Val")
	format, err := spec.format(fields)
	if err != nil {
		return nil, msgName, err
	}

	accept, err := expectedAccept(expected, spec.rulePrefix)
	if err != nil {
		return nil, msgName, err
	}
	if accept == nil {
		// A violation of some *other* rule: says nothing about this format.
		return nil, msgName, nil
	}
	return &celtolean.FormatProbe{
		Format: format, Input: val, Accept: *accept, Case: caseName,
	}, msgName, nil
}

// messageFields reads the set fields of a conformance message literal, mapping
// each to the literal text the corpus key uses ("4", "true", the raw string
// for Val). `proto.Int32(4)` / `proto.Bool(true)` wrappers are unwrapped.
func messageFields(msg *ast.CompositeLit) (map[string]string, error) {
	out := map[string]string{}
	for _, elt := range msg.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		id, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		value := kv.Value
		if call, ok := value.(*ast.CallExpr); ok && len(call.Args) == 1 {
			if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
				if x, ok := sel.X.(*ast.Ident); ok && x.Name == "proto" {
					value = call.Args[0]
				}
			}
		}
		switch v := value.(type) {
		case *ast.BasicLit:
			if v.Kind == token.STRING {
				s, err := strconv.Unquote(v.Value)
				if err != nil {
					return nil, err
				}
				out[id.Name] = s
			} else {
				out[id.Name] = v.Value
			}
		case *ast.Ident:
			if v.Name != "true" && v.Name != "false" {
				return nil, fmt.Errorf("field %s: unsupported identifier %q", id.Name, v.Name)
			}
			out[id.Name] = v.Name
		case *ast.UnaryExpr:
			// Negative version literals (`proto.Int32(-1)`).
			lit, ok := v.X.(*ast.BasicLit)
			if !ok || v.Op != token.SUB {
				return nil, fmt.Errorf("field %s: unsupported expression", id.Name)
			}
			out[id.Name] = "-" + lit.Value
		default:
			return nil, fmt.Errorf("field %s: unsupported expression", id.Name)
		}
	}
	return out, nil
}

// expectedAccept turns the case's Expected into the format's answer: true for
// results.Success, false for a results.Violations naming the format's own
// rule, and nil when the violation belongs to some other rule.
func expectedAccept(call *ast.CallExpr, rulePrefix string) (*bool, error) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return nil, fmt.Errorf("unrecognized Expected")
	}
	x, ok := sel.X.(*ast.Ident)
	if !ok || x.Name != "results" {
		return nil, fmt.Errorf("unrecognized Expected")
	}
	switch sel.Sel.Name {
	case "Success":
		if len(call.Args) != 1 {
			return nil, fmt.Errorf("results.Success: want 1 argument")
		}
		id, ok := call.Args[0].(*ast.Ident)
		if !ok || (id.Name != "true" && id.Name != "false") {
			return nil, fmt.Errorf("results.Success: non-literal argument")
		}
		if id.Name != "true" {
			// results.Success(false) would mean "validation ran but the
			// message is not valid"; unused upstream and ambiguous here.
			return nil, nil
		}
		yes := true
		return &yes, nil
	case "Violations":
		for _, id := range ruleIDs(call) {
			if id == rulePrefix || strings.HasPrefix(id, rulePrefix+"_") ||
				strings.HasPrefix(id, rulePrefix+".") {
				no := false
				return &no, nil
			}
		}
		return nil, nil
	}
	return nil, fmt.Errorf("unrecognized results.%s", sel.Sel.Name)
}

// ruleIDs collects the `RuleId: proto.String("…")` values in a Violations call.
func ruleIDs(call *ast.CallExpr) []string {
	var out []string
	ast.Inspect(call, func(n ast.Node) bool {
		kv, ok := n.(*ast.KeyValueExpr)
		if !ok {
			return true
		}
		id, ok := kv.Key.(*ast.Ident)
		if !ok || id.Name != "RuleId" {
			return true
		}
		c, ok := kv.Value.(*ast.CallExpr)
		if !ok || len(c.Args) != 1 {
			return true
		}
		if s, ok := stringLit(c.Args[0]); ok {
			out = append(out, s)
		}
		return true
	})
	return out
}

func isSelector(e ast.Expr, pkg, name string) bool {
	sel, ok := e.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != name {
		return false
	}
	x, ok := sel.X.(*ast.Ident)
	return ok && x.Name == pkg
}

func stringLit(e ast.Expr) (string, bool) {
	lit, ok := e.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	s, err := strconv.Unquote(lit.Value)
	if err != nil {
		return "", false
	}
	return s, true
}
