load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "cel2lean_lib",
    srcs = ["main.go"],
    importpath = "github.com/petersonbill64/protovalidate-lean/cmd/cel2lean",
    visibility = ["//visibility:private"],
    deps = ["//celtolean"],
)

go_binary(
    name = "cel2lean",
    embed = [":cel2lean_lib"],
    visibility = ["//visibility:public"],
)
