// cel2lean translates CEL expressions (protovalidate custom constraints) into
// Lean 4 propositions for use in subtype refinements.
//
// Single expression (reads the argument, or stdin when absent):
//
//	cel2lean 'this.size() <= 100'          →  x.size ≤ 100
//	cel2lean -var s 'this.startsWith("a")' →  s.startsWith "a"
//	cel2lean -json 'this < now'            →  {"lean": ..., "warnings": [...]}
//
// Batch mode compiles a corpus into a Lean source file asserting that every
// translation elaborates as a Prop with a Decidable instance:
//
//	cel2lean -batch corpus.tsv -namespace CelCorpus > Corpus.lean
//
// The corpus is tab-separated: name, Lean type of `this`, flags, CEL
// expression. Flags are `-` (none) or a comma list; `nodec` skips the
// Decidable instance assertion for that row. Lines starting with '#' and
// blank lines are ignored.
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"

	"github.com/petersonbill64/protovalidate-lean/celtolean"
)

func main() {
	varName := flag.String("var", "x", "Lean binder name substituted for the CEL identifier `this`")
	jsonOut := flag.Bool("json", false, "emit JSON {lean, var, kind, warnings} instead of plain text")
	batch := flag.String("batch", "", "translate a TSV corpus (name\\ttype\\tflags\\tcel) into a Lean source file on stdout; '-' reads stdin")
	namespace := flag.String("namespace", "CelCorpus", "Lean namespace for -batch output")
	imports := flag.String("import", "", "comma-separated extra Lean modules to import in -batch output")
	flag.Parse()

	if *batch != "" {
		if err := runBatch(*batch, *namespace, *varName, *imports, os.Stdout); err != nil {
			fmt.Fprintf(os.Stderr, "cel2lean: %v\n", err)
			os.Exit(1)
		}
		return
	}

	expr, err := inputExpr(flag.Args())
	if err != nil {
		fmt.Fprintf(os.Stderr, "cel2lean: %v\n", err)
		os.Exit(2)
	}
	res, err := celtolean.Translate(expr, celtolean.Options{Var: *varName})
	if err != nil {
		fmt.Fprintf(os.Stderr, "cel2lean: %v\n", err)
		os.Exit(1)
	}
	if *jsonOut {
		enc := json.NewEncoder(os.Stdout)
		enc.SetEscapeHTML(false)
		if err := enc.Encode(res); err != nil {
			fmt.Fprintf(os.Stderr, "cel2lean: %v\n", err)
			os.Exit(1)
		}
		return
	}
	for _, w := range res.Warnings {
		fmt.Fprintf(os.Stderr, "warning: %s\n", w)
	}
	fmt.Println(res.Lean)
}

func inputExpr(args []string) (string, error) {
	switch len(args) {
	case 0:
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			return "", err
		}
		if len(strings.TrimSpace(string(data))) == 0 {
			return "", fmt.Errorf("no expression given (pass as argument or on stdin)")
		}
		return string(data), nil
	case 1:
		return args[0], nil
	default:
		return "", fmt.Errorf("expected a single CEL expression argument, got %d", len(args))
	}
}

var nameRE = regexp.MustCompile(`^[a-zA-Z_][a-zA-Z0-9_]*$`)

func runBatch(path, namespace, varName, imports string, out io.Writer) error {
	var r io.Reader
	src := path
	if path == "-" {
		r, src = os.Stdin, "stdin"
	} else {
		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer f.Close()
		r = f
	}

	w := bufio.NewWriter(out)
	defer w.Flush()
	fmt.Fprintf(w, "-- Generated by cel2lean -batch from %s. Do not edit.\n", src)
	fmt.Fprintf(w, "-- Each `abbrev` asserts the translation elaborates as a Prop over its base\n")
	fmt.Fprintf(w, "-- type; each `example` asserts the proposition is Decidable (so runtime\n")
	fmt.Fprintf(w, "-- validation can construct subtype values).\n")
	fmt.Fprintf(w, "import Std\nimport Protovalidate.Cel\n")
	for _, m := range strings.Split(imports, ",") {
		if m = strings.TrimSpace(m); m != "" {
			fmt.Fprintf(w, "import %s\n", m)
		}
	}
	fmt.Fprintf(w, "\nnamespace %s\n\n", namespace)
	fmt.Fprintf(w, "set_option linter.unusedVariables false\n")

	seen := map[string]bool{}
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 1<<20), 1<<20)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := scanner.Text()
		if strings.TrimSpace(line) == "" || strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		parts := strings.Split(line, "\t")
		if len(parts) != 4 {
			return fmt.Errorf("%s:%d: expected 4 tab-separated fields (name, type, flags, cel), got %d", src, lineNo, len(parts))
		}
		name, leanType, flags, cel := strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1]), strings.TrimSpace(parts[2]), strings.TrimSpace(parts[3])
		if !nameRE.MatchString(name) {
			return fmt.Errorf("%s:%d: invalid Lean definition name %q", src, lineNo, name)
		}
		if seen[name] {
			return fmt.Errorf("%s:%d: duplicate name %q", src, lineNo, name)
		}
		seen[name] = true

		res, err := celtolean.Translate(cel, celtolean.Options{Var: varName})
		if err != nil {
			return fmt.Errorf("%s:%d (%s): %v", src, lineNo, name, err)
		}
		if res.Kind == "term" {
			return fmt.Errorf("%s:%d (%s): CEL expression is not boolean-valued; it cannot refine a subtype", src, lineNo, name)
		}
		for _, warning := range res.Warnings {
			fmt.Fprintf(os.Stderr, "%s:%d (%s): warning: %s\n", src, lineNo, name, warning)
		}

		nodec := false
		for _, f := range strings.Split(flags, ",") {
			switch strings.TrimSpace(f) {
			case "", "-":
			case "nodec":
				nodec = true
			default:
				return fmt.Errorf("%s:%d: unknown flag %q", src, lineNo, f)
			}
		}

		fmt.Fprintf(w, "\n/-- CEL: `%s` -/\n", strings.ReplaceAll(cel, "\n", " "))
		fmt.Fprintf(w, "abbrev %s (%s : %s) : Prop := %s\n", name, res.Var, leanType, res.Lean)
		if !nodec {
			fmt.Fprintf(w, "example (%s : %s) : Decidable (%s %s) := inferInstance\n", res.Var, leanType, name, res.Var)
		}
	}
	if err := scanner.Err(); err != nil {
		return err
	}
	fmt.Fprintf(w, "\nend %s\n", namespace)
	return nil
}
