package leanvalidate

import (
	"fmt"
	"sort"
	"strings"

	validatepb "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/petersonbill64/protovalidate-lean/celtolean"
)

// precAndOperand mirrors Lean's ∧ precedence: conjuncts of a multi-rule
// subtype are parenthesized when their translation binds more loosely.
const precAndOperand = 36

type fieldShape int

const (
	shapePlain  fieldShape = iota // scalar/enum, always present
	shapeOption                   // optional scalar/enum or singular message: Option
	shapeList                     // repeated: Array
	shapeMap                      // map: Std.HashMap
)

type fieldPlan struct {
	f         *protogen.Field
	protoName string
	leanName  string
	shape     fieldShape
	rules     []loweredRule
	// required unwraps Option shapes; for implicit-presence shapes a
	// non-zero rule was appended during planning.
	required bool
	// ignoreZero wraps the refinement in a zero-value escape disjunct.
	ignoreZero bool

	// thisType is the Lean type CEL's `this` denotes for the field's rules
	// (the element type under Option, the whole container for list/map).
	thisType string
	// typeText is the field's type in the validated structure.
	typeText string
	// viewName is the generated per-field CEL view function (base-typed
	// value-or-default) for Option-shaped refined/validated fields.
	viewName string
	// subBinder/props hold the subtype refinement when rules are present.
	subBinder string
	props     []string
	// nested is set when the field embeds another validated message.
	nested *msgInfo
}

func (p *fieldPlan) constrained() bool { return len(p.rules) > 0 }

// unwrapped reports whether an Option-shaped field is unwrapped by required.
func (p *fieldPlan) unwrapped() bool { return p.shape == shapeOption && p.required }

type oneofPlan struct {
	o         *protogen.Oneof
	protoName string
	leanName  string
	// required unwraps the Option (exactly one case must be set).
	required bool
	// constrained: some member carries rules or a validated payload, so a
	// validated sum type with refined constructor payloads is generated.
	constrained bool
	members     []*oneofMember
	baseSum     string // fully-qualified base sum type
	validSum    string // fully-qualified validated sum type (when constrained)
	sumLocal    string // declared name of the validated sum within the namespace
	typeText    string // the oneof field's type in the validated structure
}

type oneofMember struct {
	// plan is a synthetic per-member field plan (members are always singular,
	// so shapePlain drives the shared rule-rendering helpers).
	plan   *fieldPlan
	nested *msgInfo // validated payload for unannotated message members
	// accName is the value-or-default accessor generated for the member
	// (CEL semantics: the payload when the case is active, else the member
	// type's zero value).
	accName string
}

// ctorType is the constructor's payload type in the validated sum.
func (mem *oneofMember) ctorType() string {
	p := mem.plan
	if p.constrained() {
		return "{ " + p.subBinder + " : " + p.thisType + " // " + p.props[0] + " }"
	}
	if mem.nested != nil {
		return validQualified(mem.nested.msg)
	}
	return p.thisType
}

type propPlan struct {
	name string
	hyp  string
	text string
	rule *validatepb.Rule
}

type fileGen struct {
	cfg     Config
	msgs    map[protoreflect.FullName]*msgInfo
	targets map[string]bool
	// covered additionally includes cross-target dependency files whose
	// validated types can be referenced.
	covered map[string]bool
	notes   map[string]bool
	// regexes collects the literal patterns of every translated rule; each
	// gets a compile-time `#guard Cel.Regex.accepts` in the generated file.
	regexes map[string]bool
}

func generateFile(gen *protogen.Plugin, f *protogen.File, cfg Config, msgs map[protoreflect.FullName]*msgInfo, targets, covered map[string]bool) error {
	fg := &fileGen{cfg: cfg, msgs: msgs, targets: targets, covered: covered, notes: map[string]bool{}, regexes: map[string]bool{}}

	// Messages of this file needing a validated variant, topologically sorted
	// so embedded validated types are declared before their containers.
	var order []*msgInfo
	seen := map[protoreflect.FullName]bool{}
	var dfs func(mi *msgInfo)
	dfs = func(mi *msgInfo) {
		name := mi.msg.Desc.FullName()
		if seen[name] {
			return
		}
		seen[name] = true
		for _, fd := range mi.msg.Fields {
			if dep := validFieldEdge(mi, fd, msgs, covered); dep != nil && dep.needsValid &&
				dep.msg.Desc.ParentFile().Path() == f.Desc.Path() {
				dfs(dep)
			}
		}
		order = append(order, mi)
	}
	for _, m := range f.Messages {
		walkMessages(m, func(m *protogen.Message) {
			if mi := msgs[m.Desc.FullName()]; mi != nil && mi.needsValid {
				dfs(mi)
			}
		})
	}

	out := gen.NewGeneratedFile(protoStem(f.Desc.Path())+".lean", "")
	out.P("-- Generated by protoc-gen-lean-protovalidate. Do not edit.")
	out.P("-- Source: ", f.Desc.Path())
	out.P("module")
	out.P()
	if len(order) == 0 {
		out.P("-- No messages with protovalidate rules.")
		return nil
	}

	body := &strings.Builder{}
	for _, mi := range order {
		if err := fg.emitMessage(body, mi); err != nil {
			return fmt.Errorf("message %s: %w", mi.msg.Desc.FullName(), err)
		}
	}

	out.P("public import Protovalidate.Cel")
	out.P("public import Protovalidate.Runtime")
	if len(fg.regexes) > 0 {
		// #guard evaluates Cel.Regex.accepts at elaboration time, which needs
		// the implementation meta-imported under the module system.
		out.P("meta import Protovalidate.Cel.Regex")
	}
	out.P("public import ", cfg.BasePrefix, ".", protoStem(f.Desc.Path()))
	imports := f.Desc.Imports()
	for i := 0; i < imports.Len(); i++ {
		dep := imports.Get(i)
		if targets[dep.Path()] {
			out.P("public import ", cfg.BasePrefix, ".", protoStem(dep.Path()))
			out.P("public import ", cfg.Prefix, ".", protoStem(dep.Path()))
		} else if dm, ok := cfg.DepModules[dep.Path()]; ok {
			out.P("public import ", dm.Base, ".", protoStem(dep.Path()))
			out.P("public import ", dm.Valid, ".", protoStem(dep.Path()))
		}
	}
	out.P()
	out.P("public section")
	out.P()
	out.P("set_option linter.unusedVariables false")
	out.P()
	if len(fg.regexes) > 0 {
		out.P("-- Acceptance backstop: every literal regex must be inside the subset the")
		out.P("-- Lean engine (Cel.Regex) supports — an unsupported pattern would match")
		out.P("-- nothing at runtime, which is unsound under negation. A failing guard")
		out.P("-- means the generator's Go-side gate and the Lean engine disagree.")
		regexes := make([]string, 0, len(fg.regexes))
		for re := range fg.regexes {
			regexes = append(regexes, re)
		}
		sort.Strings(regexes)
		for _, re := range regexes {
			out.P("#guard Cel.Regex.accepts ", celtolean.LeanString(re))
		}
		out.P()
	}
	if len(fg.notes) > 0 {
		out.P("/- cel2lean translation notes:")
		notes := make([]string, 0, len(fg.notes))
		for n := range fg.notes {
			notes = append(notes, n)
		}
		sort.Strings(notes)
		for _, n := range notes {
			out.P("   - ", docText(n))
		}
		out.P("-/")
		out.P()
	}
	out.P("namespace ", validNamespace(f.Desc.Package()))
	out.P()
	out.P(strings.TrimRight(body.String(), "\n"))
	out.P()
	out.P("end ", validNamespace(f.Desc.Package()))
	return nil
}

func (fg *fileGen) translate(cel string, opts celtolean.Options) (*celtolean.Result, error) {
	res, err := celtolean.Translate(cel, opts)
	if err != nil {
		return nil, err
	}
	if res.Kind == "term" {
		return nil, fmt.Errorf("CEL expression %q is not boolean-valued", cel)
	}
	for _, w := range res.Warnings {
		fg.notes[w] = true
	}
	for _, re := range res.Regexes {
		fg.regexes[re] = true
	}
	return res, nil
}

func violation(fieldPath, id, message string) string {
	return "Except.error { fieldPath := " + celtolean.LeanString(fieldPath) +
		", ruleId := " + celtolean.LeanString(id) +
		", message := " + celtolean.LeanString(message) + " }"
}

func ruleViolation(fieldPath string, r loweredRule) string {
	msg := r.message
	if msg == "" {
		msg = r.cel
	}
	return violation(fieldPath, r.id, msg)
}

// iteChain renders nested dependent ifs deciding each rule, yielding ok with
// all hypotheses in scope or the violation of the first failing rule.
func iteChain(w *strings.Builder, indent string, hyps, conds []string, ok string, errs []string) {
	if len(conds) == 0 {
		w.WriteString(indent + ok + "\n")
		return
	}
	w.WriteString(indent + "if " + hyps[0] + " : " + conds[0] + " then\n")
	iteChain(w, indent+"  ", hyps[1:], conds[1:], ok, errs[1:])
	w.WriteString(indent + "else " + errs[0] + "\n")
}

// zeroEscape is the Lean proposition "the value is its protobuf zero value",
// used by ignoreZero refinements. The subject must be atomic.
func zeroEscape(p *fieldPlan, subject string) string {
	switch p.shape {
	case shapeList, shapeMap:
		return subject + ".isEmpty"
	case shapeOption, shapePlain:
	}
	switch p.f.Desc.Kind() {
	case protoreflect.StringKind:
		return subject + ".isEmpty"
	case protoreflect.BytesKind:
		return subject + ".size = 0"
	case protoreflect.BoolKind:
		return subject + " = false"
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return subject + " = 0.0"
	case protoreflect.EnumKind:
		if zero := p.f.Enum.Desc.Values().ByNumber(0); zero != nil {
			return "(" + subject + " matches ." + celtolean.LeanIdent(string(zero.Name())) + ")"
		}
		return subject + " = default"
	default:
		return subject + " = 0"
	}
}

// requiredRule encodes protovalidate `required` on implicit-presence shapes
// as a non-zero rule (explicit-presence fields are structurally unwrapped
// instead).
func requiredRule(p *fieldPlan) loweredRule {
	kind := p.f.Desc.Kind()
	shape := p.shape
	enum := p.f.Enum
	return loweredRule{
		id:      "required",
		message: "value is required",
		direct: func(_ *fileGen, subject string) (string, int, error) {
			switch shape {
			case shapeList, shapeMap:
				return "¬" + subject + ".isEmpty", 40, nil
			}
			switch kind {
			case protoreflect.StringKind:
				return "¬" + subject + ".isEmpty", 40, nil
			case protoreflect.BytesKind:
				return subject + ".size ≠ 0", 50, nil
			case protoreflect.BoolKind:
				return subject + " = true", 50, nil
			case protoreflect.FloatKind, protoreflect.DoubleKind:
				return subject + " ≠ 0.0", 50, nil
			case protoreflect.EnumKind:
				if enum != nil {
					if zero := enum.Desc.Values().ByNumber(0); zero != nil {
						return "¬(" + subject + " matches ." + celtolean.LeanIdent(string(zero.Name())) + ")", 40, nil
					}
				}
				return subject + " ≠ default", 50, nil
			default:
				return subject + " ≠ 0", 50, nil
			}
		},
	}
}

// renderProps renders every rule of a field against a subject, parenthesized
// for conjunction, with the zero-escape disjunct applied when ignoreZero.
func (fg *fileGen) renderProps(p *fieldPlan, subject string) (string, error) {
	parts := make([]string, 0, len(p.rules))
	for _, r := range p.rules {
		t, prec, err := fg.renderRule(r, subject)
		if err != nil {
			return "", fmt.Errorf("field %s: %w", p.protoName, err)
		}
		if len(p.rules) > 1 && prec < precAndOperand {
			t = "(" + t + ")"
		}
		parts = append(parts, t)
	}
	conj := strings.Join(parts, " ∧ ")
	if p.ignoreZero {
		return zeroEscape(p, subject) + " ∨ (" + conj + ")", nil
	}
	return conj, nil
}

// validateChain renders the dite chain deciding a field's rules, including
// the ignoreZero escape, yielding okOf(proof term text).
func (fg *fileGen) validateChain(w *strings.Builder, indent string, p *fieldPlan, subject, fieldPath string,
	okOf func(proof string) string) error {
	conds := make([]string, 0, len(p.rules))
	errs := make([]string, 0, len(p.rules))
	hyps := make([]string, 0, len(p.rules))
	for i, r := range p.rules {
		t, _, err := fg.renderRule(r, subject)
		if err != nil {
			return fmt.Errorf("field %s: %w", p.protoName, err)
		}
		conds = append(conds, t)
		hyps = append(hyps, fmt.Sprintf("h%d", i))
		errs = append(errs, ruleViolation(fieldPath, r))
	}
	proof := "⟨" + strings.Join(hyps, ", ") + "⟩"
	if len(hyps) == 1 {
		proof = hyps[0]
	}
	if p.ignoreZero {
		w.WriteString(indent + "if h_z : " + zeroEscape(p, subject) + " then " + okOf("Or.inl h_z") + "\n")
		w.WriteString(indent + "else\n")
		iteChain(w, indent+"  ", hyps, conds, okOf("Or.inr "+proof), errs)
		return nil
	}
	iteChain(w, indent, hyps, conds, okOf(proof), errs)
	return nil
}

func (fg *fileGen) emitMessage(w *strings.Builder, mi *msgInfo) error {
	m := mi.msg
	local := localName(m)
	base := baseQualified(m.Desc.FullName())

	// Names already claimed by struct fields/oneofs (locals in validate).
	taken := map[string]bool{}
	// Identifiers used inside any of the message's rules: binders must dodge
	// them so translations cannot capture.
	ruleIdents := map[string]bool{}
	addIdents := func(rules []loweredRule) {
		for _, r := range rules {
			for id := range r.idents {
				ruleIdents[id] = true
			}
		}
	}

	// ---- plan fields -------------------------------------------------------
	var fields []*fieldPlan
	for _, fd := range m.Fields {
		if fd.Oneof != nil && !fd.Oneof.Desc.IsSynthetic() {
			continue // carried through the oneof sum type below
		}
		set := mi.fieldRules[string(fd.Desc.Name())]
		p := &fieldPlan{
			f:          fd,
			protoName:  string(fd.Desc.Name()),
			leanName:   celtolean.LeanIdent(string(fd.Desc.Name())),
			rules:      set.rules,
			required:   set.required,
			ignoreZero: set.ignoreZero,
		}
		taken[p.protoName] = true
		addIdents(p.rules)
		switch {
		case fd.Desc.IsMap():
			k, err := scalarText(fd.Desc.MapKey().Kind(), nil, nil)
			if err != nil {
				return fmt.Errorf("field %s key: %w", p.protoName, err)
			}
			vd := fd.Desc.MapValue()
			var vmsg protoreflect.MessageDescriptor
			var venum protoreflect.EnumDescriptor
			if vd.Kind() == protoreflect.MessageKind {
				vmsg = vd.Message()
			} else if vd.Kind() == protoreflect.EnumKind {
				venum = vd.Enum()
			}
			v, err := scalarText(vd.Kind(), venum, vmsg)
			if err != nil {
				return fmt.Errorf("field %s value: %w", p.protoName, err)
			}
			p.shape = shapeMap
			p.thisType = "Std.HashMap " + k + " " + v
		case fd.Desc.IsList():
			elem, err := scalarText(fd.Desc.Kind(), enumDesc(fd), msgDesc(fd))
			if err != nil {
				return fmt.Errorf("field %s: %w", p.protoName, err)
			}
			p.shape = shapeList
			p.thisType = "Array " + elem
		case fd.Desc.Kind() == protoreflect.MessageKind:
			p.shape = shapeOption
			p.thisType = baseQualified(fd.Desc.Message().FullName())
		case fd.Desc.HasOptionalKeyword():
			elem, err := scalarText(fd.Desc.Kind(), enumDesc(fd), msgDesc(fd))
			if err != nil {
				return fmt.Errorf("field %s: %w", p.protoName, err)
			}
			p.shape = shapeOption
			p.thisType = elem
		default:
			elem, err := scalarText(fd.Desc.Kind(), enumDesc(fd), msgDesc(fd))
			if err != nil {
				return fmt.Errorf("field %s: %w", p.protoName, err)
			}
			p.shape = shapePlain
			p.thisType = elem
		}
		// required on implicit-presence shapes is an ordinary non-zero rule;
		// on Option shapes it structurally unwraps (handled below).
		if p.required && p.shape != shapeOption {
			p.rules = append([]loweredRule{requiredRule(p)}, p.rules...)
		}
		fields = append(fields, p)
	}
	msgRuleIdents := func() error {
		for _, r := range mi.msgRules {
			ids, err := celtolean.Idents(r.GetExpression())
			if err != nil {
				return fmt.Errorf("message rule %q: %w", r.GetId(), err)
			}
			for id := range ids {
				ruleIdents[id] = true
			}
		}
		return nil
	}
	if err := msgRuleIdents(); err != nil {
		return err
	}

	// Validated element types and subtype refinements.
	for _, p := range fields {
		if dep := validFieldEdge(mi, p.f, fg.msgs, fg.covered); dep != nil && dep.needsValid {
			p.nested = dep
			if p.shape == shapeList {
				// Rules on a repeated-message field refine the array of
				// *validated* elements, composing the structural list rule
				// with per-element validation.
				p.thisType = "Array " + validQualified(dep.msg)
			}
		}
		if !p.constrained() {
			continue
		}
		p.subBinder = freshTaken("x", ruleIdents)
		props, err := fg.renderProps(p, p.subBinder)
		if err != nil {
			return err
		}
		p.props = []string{props}
	}

	// Name the CEL view functions (emitted later, referenced by ThisFields).
	for _, p := range fields {
		if p.shape == shapeOption && !p.unwrapped() && (p.constrained() || p.nested != nil) {
			p.viewName = celtolean.LeanIdent(uniqueName(p.protoName+"D", taken))
		}
	}

	// Struct field type text.
	for _, p := range fields {
		inner := p.thisType
		if p.constrained() {
			inner = "{ " + p.subBinder + " : " + p.thisType + " // " + p.props[0] + " }"
		} else if p.nested != nil {
			switch p.shape {
			case shapeOption:
				inner = validQualified(p.nested.msg)
			case shapeList:
				inner = "Array " + validQualified(p.nested.msg)
			}
		}
		if p.shape == shapeOption && !p.unwrapped() {
			p.typeText = "Option " + wrapType(inner)
		} else {
			p.typeText = inner
		}
	}

	// Oneofs (real ones). Members with rules (or validated message payloads)
	// yield a validated sum type whose constructors carry the refined
	// payloads; (buf.validate.oneof).required unwraps the Option.
	var oneofs []*oneofPlan
	for _, o := range m.Oneofs {
		if o.Desc.IsSynthetic() {
			continue
		}
		name := string(o.Desc.Name())
		taken[name] = true
		op := &oneofPlan{
			o:         o,
			protoName: name,
			leanName:  celtolean.LeanIdent(name),
			required:  oneofRequired(o),
			baseSum:   base + "." + celtolean.LeanIdent(name+"_Type"),
			sumLocal:  local + "." + celtolean.LeanIdent(name+"_Type"),
			validSum:  validQualified(m) + "." + celtolean.LeanIdent(name+"_Type"),
		}
		for _, fd := range o.Fields {
			set := mi.fieldRules[string(fd.Desc.Name())]
			if set.required {
				fg.notes[fmt.Sprintf("field %s.%s: `required` on a oneof member is ignored (the active case already implies presence; use (buf.validate.oneof).required)",
					m.Desc.FullName(), fd.Desc.Name())] = true
			}
			p := &fieldPlan{
				f:          fd,
				protoName:  string(fd.Desc.Name()),
				leanName:   celtolean.LeanIdent(string(fd.Desc.Name())),
				shape:      shapePlain,
				rules:      set.rules,
				ignoreZero: set.ignoreZero,
			}
			addIdents(p.rules)
			var payload string
			var perr error
			if fd.Desc.Kind() == protoreflect.MessageKind {
				payload = baseQualified(fd.Desc.Message().FullName())
			} else {
				payload, perr = scalarText(fd.Desc.Kind(), enumDesc(fd), msgDesc(fd))
				if perr != nil {
					return fmt.Errorf("oneof member %s: %w", p.protoName, perr)
				}
			}
			p.thisType = payload
			mem := &oneofMember{plan: p}
			if dep := validFieldEdge(mi, fd, fg.msgs, fg.covered); dep != nil && dep.needsValid {
				mem.nested = dep
			}
			op.members = append(op.members, mem)
		}
		memberNames := map[string]bool{}
		for _, mem := range op.members {
			memberNames[mem.plan.protoName] = true
			if mem.plan.constrained() || mem.nested != nil {
				op.constrained = true
			}
		}
		for _, mem := range op.members {
			mem.accName = celtolean.LeanIdent(uniqueName(mem.plan.protoName+"_or_default", memberNames))
		}
		inner := op.baseSum
		if op.constrained {
			inner = op.validSum
		}
		if op.required {
			op.typeText = inner
		} else {
			op.typeText = "Option (" + inner + ")"
		}
		oneofs = append(oneofs, op)
	}
	// Render member refinements (all rule identifiers are collected by now).
	for _, op := range oneofs {
		for _, mem := range op.members {
			p := mem.plan
			if !p.constrained() {
				continue
			}
			p.subBinder = freshTaken("x", ruleIdents)
			props, err := fg.renderProps(p, p.subBinder)
			if err != nil {
				return err
			}
			p.props = []string{props}
		}
	}

	// Message-level rules become dependent Prop fields over the value fields.
	// Text is the field's CEL value: base-typed, value-or-default for
	// presence fields — so rules traverse one hop into message fields
	// (`this.featured.sku`) with CEL's default-instance semantics.
	thisFields := map[string]celtolean.ThisField{}
	for _, p := range fields {
		text := p.leanName
		if p.constrained() && (p.shape != shapeOption || p.unwrapped()) {
			text = p.leanName + ".val"
		}
		has := p.hasText(text)
		if p.unwrapped() {
			has = "true" // required fields are always present
		}
		value := p.celValueText()
		if p.viewName != "" {
			value = "(" + local + "." + p.viewName + " " + p.leanName + ")"
		}
		thisFields[p.protoName] = celtolean.ThisField{Text: value, Has: has}
	}
	for _, op := range oneofs {
		accessorHome := op.sumLocal
		if !op.constrained {
			accessorHome = op.baseSum
		}
		for _, mem := range op.members {
			// Presence is a case test on the sum; value access follows CEL's
			// value-or-default semantics via the generated accessor.
			caseTest := op.leanName + " matches ." + mem.plan.leanName + " _"
			text := op.leanName + "." + mem.accName
			if !op.required {
				caseTest = op.leanName + ".any (· matches ." + mem.plan.leanName + " _)"
				text = "(" + accessorHome + "." + mem.accName + " " + op.leanName + ")"
			}
			thisFields[mem.plan.protoName] = celtolean.ThisField{Text: text, Has: caseTest}
		}
	}
	var props []*propPlan
	for i, r := range mi.msgRules {
		attrs, err := pathAttrsForMessage(m.Desc, r.GetExpression())
		if err != nil {
			return fmt.Errorf("message rule %q: %w", r.GetId(), err)
		}
		res, err := fg.translate(r.GetExpression(), celtolean.Options{ThisFields: thisFields, PathAttrs: attrs})
		if err != nil {
			return fmt.Errorf("message rule %q: %w", r.GetId(), err)
		}
		props = append(props, &propPlan{
			name: uniqueName(sanitizeRuleID(r.GetId(), i), taken),
			text: res.Lean,
			rule: r,
		})
	}

	// validate-scope binders, dodging fields, props, and every rule ident.
	binderTaken := map[string]bool{}
	for k := range taken {
		binderTaken[k] = true
	}
	for k := range ruleIdents {
		binderTaken[k] = true
	}
	bName := uniqueName("b", binderTaken)
	for _, pr := range props {
		pr.hyp = uniqueName("h_"+pr.name, binderTaken)
	}

	// ---- validated oneof sums ------------------------------------------------
	for _, op := range oneofs {
		if !op.constrained {
			continue
		}
		if err := fg.emitOneofSum(w, m, op, ruleIdents); err != nil {
			return err
		}
	}
	// Value-or-default accessors (CEL member access semantics) for every real
	// oneof: on the validated sum for constrained oneofs, extending the base
	// sum's namespace otherwise.
	for _, op := range oneofs {
		emitOneofAccessors(w, op)
	}

	// CEL view functions for Option-shaped refined/validated fields: the
	// base-typed value when set, the zero value otherwise. Message rules
	// select through these (plain Option fields inline `getD` directly, and
	// deeper hops use the base codegen's `<field>D` getters).
	for _, p := range fields {
		if p.viewName == "" {
			continue
		}
		body := "(" + p.leanName + ".map Subtype.val).getD " + p.defaultText()
		if !p.constrained() {
			body = "(" + p.leanName + ".map " + validQualified(p.nested.msg) + ".toBase).getD default"
		}
		fmt.Fprintf(w, "/-- CEL value view for `%s`: the base-typed value when set, its zero value otherwise. -/\n",
			p.protoName)
		fmt.Fprintf(w, "def %s.%s (%s : %s) : %s :=\n  %s\n\n",
			local, p.viewName, p.leanName, p.typeText, p.thisType, body)
	}

	// ---- structure ----------------------------------------------------------
	fmt.Fprintf(w, "/-- Validated `%s`: refinement of `%s` by its protovalidate rules. -/\n",
		m.Desc.FullName(), string(m.Desc.FullName()))
	fmt.Fprintf(w, "structure %s where\n", local)
	for _, p := range fields {
		if len(p.rules) > 0 || p.required {
			docs := make([]string, 0, len(p.rules)+1)
			if p.unwrapped() {
				docs = append(docs, "required")
			}
			for _, r := range p.rules {
				d := r.id
				if r.cel != "" {
					d = fmt.Sprintf("`%s` (%s)", docText(r.cel), docText(r.id))
				}
				docs = append(docs, d)
			}
			fmt.Fprintf(w, "  /-- %s -/\n", strings.Join(docs, "; "))
		}
		fmt.Fprintf(w, "  %s : %s\n", p.leanName, p.typeText)
	}
	for _, op := range oneofs {
		if op.required {
			fmt.Fprintf(w, "  /-- required: exactly one case must be set -/\n")
		}
		fmt.Fprintf(w, "  %s : %s\n", op.leanName, op.typeText)
	}
	for _, pr := range props {
		fmt.Fprintf(w, "  /-- CEL: `%s` (%s) -/\n", docText(pr.rule.GetExpression()), docText(pr.rule.GetId()))
		fmt.Fprintf(w, "  %s : %s\n", pr.name, pr.text)
	}
	w.WriteString("\n")

	// ---- validate ------------------------------------------------------------
	fmt.Fprintf(w, "/-- Decide every protovalidate rule on a `%s`, producing the validated refinement or the first violation. -/\n",
		string(m.Desc.FullName()))
	fmt.Fprintf(w, "def %s.validate (%s : %s) : Except _root_.Protovalidate.Violation %s := do\n",
		local, bName, base, local)
	for _, p := range fields {
		access := bName + "." + p.leanName
		switch {
		case p.constrained() && p.shape != shapeOption:
			if p.nested != nil && p.shape == shapeList {
				// Validate elements first; the list rules then refine the
				// array of validated elements.
				elems := freshTaken(p.protoName+"_elems", union(binderTaken, ruleIdents))
				fmt.Fprintf(w, "  let %s ← %s.mapM %s.validate\n", elems, access, validQualified(p.nested.msg))
				access = elems
			}
			fmt.Fprintf(w, "  let %s : %s ←\n", p.leanName, p.typeText)
			okOf := func(proof string) string { return "Except.ok ⟨" + access + ", " + proof + "⟩" }
			if err := fg.validateChain(w, "    ", p, access, p.protoName, okOf); err != nil {
				return err
			}
		case p.shape == shapeOption && (p.constrained() || p.required):
			vName := freshTaken("v", union(binderTaken, ruleIdents))
			fmt.Fprintf(w, "  let %s : %s ←\n", p.leanName, p.typeText)
			fmt.Fprintf(w, "    match %s with\n", access)
			if p.required {
				fmt.Fprintf(w, "    | none => %s\n", violation(p.protoName, "required", "value is required"))
			} else {
				fmt.Fprintf(w, "    | none => Except.ok none\n")
			}
			fmt.Fprintf(w, "    | some %s =>\n", vName)
			switch {
			case p.constrained():
				okOf := func(proof string) string {
					if p.unwrapped() {
						return "Except.ok ⟨" + vName + ", " + proof + "⟩"
					}
					return "Except.ok (some ⟨" + vName + ", " + proof + "⟩)"
				}
				if err := fg.validateChain(w, "      ", p, vName, p.protoName, okOf); err != nil {
					return err
				}
			case p.nested != nil:
				if p.unwrapped() {
					fmt.Fprintf(w, "      %s.validate %s\n", validQualified(p.nested.msg), vName)
				} else {
					fmt.Fprintf(w, "      (%s.validate %s).map some\n", validQualified(p.nested.msg), vName)
				}
			default: // required, no rules
				fmt.Fprintf(w, "      Except.ok %s\n", vName)
			}
		case p.nested != nil && p.shape == shapeOption:
			vName := freshTaken("v", binderTaken)
			fmt.Fprintf(w, "  let %s ← match %s with\n", p.leanName, access)
			fmt.Fprintf(w, "    | none => Except.ok none\n")
			fmt.Fprintf(w, "    | some %s => (%s.validate %s).map some\n", vName, validQualified(p.nested.msg), vName)
		case p.nested != nil && p.shape == shapeList:
			fmt.Fprintf(w, "  let %s ← %s.mapM %s.validate\n", p.leanName, access, validQualified(p.nested.msg))
		default:
			fmt.Fprintf(w, "  let %s := %s\n", p.leanName, access)
		}
	}
	for _, op := range oneofs {
		access := bName + "." + op.leanName
		switch {
		case op.required && op.constrained:
			fmt.Fprintf(w, "  let %s : %s ← match %s with\n", op.leanName, op.validSum, access)
			fmt.Fprintf(w, "    | none => %s\n",
				violation(op.protoName, "required", "exactly one field of oneof "+op.protoName+" must be set"))
			fmt.Fprintf(w, "    | some v => %s.validate v\n", op.validSum)
		case op.required:
			fmt.Fprintf(w, "  let %s ← match %s with\n", op.leanName, access)
			fmt.Fprintf(w, "    | none => %s\n",
				violation(op.protoName, "required", "exactly one field of oneof "+op.protoName+" must be set"))
			fmt.Fprintf(w, "    | some v => Except.ok v\n")
		case op.constrained:
			fmt.Fprintf(w, "  let %s ← match %s with\n", op.leanName, access)
			fmt.Fprintf(w, "    | none => Except.ok none\n")
			fmt.Fprintf(w, "    | some v => (%s.validate v).map some\n", op.validSum)
		default:
			fmt.Fprintf(w, "  let %s := %s\n", op.leanName, access)
		}
	}
	var assigns []string
	for _, p := range fields {
		assigns = append(assigns, p.leanName+" := "+p.leanName)
	}
	for _, op := range oneofs {
		assigns = append(assigns, op.leanName+" := "+op.leanName)
	}
	for _, pr := range props {
		assigns = append(assigns, pr.name+" := "+pr.hyp)
	}
	finalOk := "Except.ok { " + strings.Join(assigns, ", ") + " }"
	if len(assigns) == 0 {
		finalOk = "Except.ok {}"
	}
	var propConds, propHyps, propErrs []string
	for _, pr := range props {
		propConds = append(propConds, pr.text)
		propHyps = append(propHyps, pr.hyp)
		msg := pr.rule.GetMessage()
		if msg == "" {
			msg = pr.rule.GetExpression()
		}
		propErrs = append(propErrs, violation("", pr.rule.GetId(), msg))
	}
	iteChain(w, "  ", propHyps, propConds, finalOk, propErrs)
	w.WriteString("\n")

	// ---- toBase ---------------------------------------------------------------
	fmt.Fprintf(w, "/-- Forget the refinements (any unknown fields are dropped). -/\n")
	fmt.Fprintf(w, "def %s.toBase (v : %s) : %s :=\n", local, local, base)
	var backs []string
	for _, p := range fields {
		expr := "v." + p.leanName
		switch {
		case p.unwrapped():
			switch {
			case p.constrained():
				expr = "some " + expr + ".val"
			case p.nested != nil:
				expr = "some " + expr + ".toBase"
			default:
				expr = "some " + expr
			}
		case p.constrained() && p.shape != shapeOption:
			expr += ".val"
			if p.nested != nil {
				expr += ".map (·.toBase)"
			}
		case p.constrained():
			expr += ".map (·.val)"
		case p.nested != nil:
			expr += ".map (·.toBase)"
		}
		backs = append(backs, p.leanName+" := "+expr)
	}
	for _, op := range oneofs {
		expr := "v." + op.leanName
		switch {
		case op.required && op.constrained:
			expr = "some " + expr + ".toBase"
		case op.required:
			expr = "some " + expr
		case op.constrained:
			expr += ".map (·.toBase)"
		}
		backs = append(backs, op.leanName+" := "+expr)
	}
	if len(backs) == 0 {
		w.WriteString("  {}\n\n")
	} else {
		w.WriteString("  { " + strings.Join(backs, ",\n    ") + " }\n\n")
	}

	// ---- decodeValid ------------------------------------------------------------
	fmt.Fprintf(w, "/-- Decode the wire format and validate in one step. -/\n")
	fmt.Fprintf(w, "def %s.decodeValid (bytes : ByteArray) : Except String %s :=\n", local, local)
	fmt.Fprintf(w, "  match %s.decode bytes with\n", base)
	fmt.Fprintf(w, "  | .error e => .error (toString e)\n")
	fmt.Fprintf(w, "  | .ok msg => (%s.validate msg).mapError toString\n\n", local)
	return nil
}

// emitOneofSum generates the validated sum type for a constrained oneof: an
// inductive whose constructors carry refined payloads, with case-wise
// validate/toBase.
func (fg *fileGen) emitOneofSum(w *strings.Builder, m *protogen.Message, op *oneofPlan, ruleIdents map[string]bool) error {
	fmt.Fprintf(w, "/-- Validated `%s.%s`: the oneof sum with refined constructor payloads. -/\n",
		m.Desc.FullName(), op.protoName)
	fmt.Fprintf(w, "inductive %s where\n", op.sumLocal)
	for _, mem := range op.members {
		p := mem.plan
		if len(p.rules) > 0 {
			docs := make([]string, 0, len(p.rules))
			for _, r := range p.rules {
				d := r.id
				if r.cel != "" {
					d = fmt.Sprintf("`%s` (%s)", docText(r.cel), docText(r.id))
				}
				docs = append(docs, d)
			}
			fmt.Fprintf(w, "  /-- %s -/\n", strings.Join(docs, "; "))
		}
		fmt.Fprintf(w, "  | %s : %s → %s\n", p.leanName, mem.ctorType(), op.sumLocal)
	}
	w.WriteString("\n")

	taken := map[string]bool{}
	for k := range ruleIdents {
		taken[k] = true
	}
	bName := freshTaken("b", taken)
	taken[bName] = true

	fmt.Fprintf(w, "/-- Decide the member rules for the active case. -/\n")
	fmt.Fprintf(w, "def %s.validate (%s : %s) : Except _root_.Protovalidate.Violation %s :=\n",
		op.sumLocal, bName, op.baseSum, op.sumLocal)
	fmt.Fprintf(w, "  match %s with\n", bName)
	for _, mem := range op.members {
		p := mem.plan
		vName := freshTaken("v", taken)
		switch {
		case p.constrained():
			fmt.Fprintf(w, "  | .%s %s =>\n", p.leanName, vName)
			okOf := func(proof string) string {
				return "Except.ok (." + p.leanName + " ⟨" + vName + ", " + proof + "⟩)"
			}
			if err := fg.validateChain(w, "    ", p, vName, p.protoName, okOf); err != nil {
				return fmt.Errorf("oneof %s: %w", op.protoName, err)
			}
		case mem.nested != nil:
			fmt.Fprintf(w, "  | .%s %s => (%s.validate %s).map (fun x => .%s x)\n",
				p.leanName, vName, validQualified(mem.nested.msg), vName, p.leanName)
		default:
			fmt.Fprintf(w, "  | .%s %s => Except.ok (.%s %s)\n", p.leanName, vName, p.leanName, vName)
		}
	}
	w.WriteString("\n")

	fmt.Fprintf(w, "/-- Forget the refinements. -/\n")
	fmt.Fprintf(w, "def %s.toBase (v : %s) : %s :=\n", op.sumLocal, op.sumLocal, op.baseSum)
	fmt.Fprintf(w, "  match v with\n")
	for _, mem := range op.members {
		p := mem.plan
		switch {
		case p.constrained():
			fmt.Fprintf(w, "  | .%s x => .%s x.val\n", p.leanName, p.leanName)
		case mem.nested != nil:
			fmt.Fprintf(w, "  | .%s x => .%s x.toBase\n", p.leanName, p.leanName)
		default:
			fmt.Fprintf(w, "  | .%s x => .%s x\n", p.leanName, p.leanName)
		}
	}
	w.WriteString("\n")
	return nil
}

// celValueText is the Lean expression for the field's CEL value in message
// rules: base-typed, with value-or-default semantics for presence fields
// (unset message fields read as the default instance, unset optional scalars
// as their zero value). Refinements project away (`.val`/`.toBase`) so
// selects reach base fields.
func (p *fieldPlan) celValueText() string {
	name := p.leanName
	switch p.shape {
	case shapeOption:
		if p.unwrapped() { // required: always present
			switch {
			case p.constrained():
				return name + ".val"
			case p.nested != nil:
				return name + ".toBase"
			default:
				return name
			}
		}
		switch {
		case p.constrained():
			// Explicit Subtype.val: cdot lambdas cannot infer their argument
			// type in structure-field positions.
			return "((" + name + ".map Subtype.val).getD " + p.defaultText() + ")"
		case p.nested != nil:
			return "((" + name + ".map " + validQualified(p.nested.msg) + ".toBase).getD default)"
		default:
			return "(" + name + ".getD " + p.defaultText() + ")"
		}
	case shapeList:
		base := name
		if p.constrained() {
			base = name + ".val"
		}
		if p.nested != nil {
			return "(" + base + ".map " + validQualified(p.nested.msg) + ".toBase)"
		}
		return base
	default:
		if p.constrained() {
			return name + ".val"
		}
		return name
	}
}

// defaultText is the zero value of the field's element type.
func (p *fieldPlan) defaultText() string {
	if p.f.Desc.Kind() == protoreflect.MessageKind {
		return "default"
	}
	return defaultValueText(p.f)
}

// defaultValueText is the Lean expression for a member type's protobuf zero
// value (CEL's result when accessing an inactive oneof member).
func defaultValueText(fd *protogen.Field) string {
	switch fd.Desc.Kind() {
	case protoreflect.StringKind:
		return `""`
	case protoreflect.BoolKind:
		return "false"
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return "0.0"
	case protoreflect.EnumKind:
		if fd.Enum != nil {
			if zero := fd.Enum.Desc.Values().ByNumber(0); zero != nil {
				return "." + celtolean.LeanIdent(string(zero.Name()))
			}
		}
		return "default"
	case protoreflect.BytesKind, protoreflect.MessageKind, protoreflect.GroupKind:
		return "default"
	default:
		return "0"
	}
}

// emitOneofAccessors generates one value-or-default accessor per member,
// mirroring CEL's semantics for oneof member access: the payload (as its
// *base* type) when that case is active, the member type's zero value
// otherwise. The accessor takes the field's exact shape — the bare sum for
// required oneofs (dot notation), Option-wrapped otherwise.
func emitOneofAccessors(w *strings.Builder, op *oneofPlan) {
	home := op.sumLocal
	if !op.constrained {
		home = op.baseSum
	}
	argType := home
	if !op.required {
		argType = "Option (" + home + ")"
	}
	for _, mem := range op.members {
		p := mem.plan
		result := "v"
		switch {
		case p.constrained():
			result = "v.val"
		case mem.nested != nil:
			result = "v.toBase"
		}
		pattern := "." + p.leanName + " v"
		if !op.required {
			pattern = "some (." + p.leanName + " v)"
		}
		fmt.Fprintf(w, "/-- CEL value-or-default access for `%s`: the payload when the case is active, `%s` otherwise. -/\n",
			p.protoName, defaultValueText(p.f))
		fmt.Fprintf(w, "def %s.%s : %s → %s\n", home, mem.accName, argType, p.thisType)
		fmt.Fprintf(w, "  | %s => %s\n", pattern, result)
		fmt.Fprintf(w, "  | _ => %s\n\n", defaultValueText(p.f))
	}
}

// hasText renders the Bool expression deciding CEL has(this.f) for the field,
// given the Lean text of the field's value. Explicit-presence fields test the
// Option; implicit-presence fields test non-default per CEL's proto semantics.
func (p *fieldPlan) hasText(text string) string {
	switch p.shape {
	case shapeOption:
		return p.leanName + ".isSome"
	case shapeList, shapeMap:
		return "!" + text + ".isEmpty"
	}
	switch p.f.Desc.Kind() {
	case protoreflect.StringKind:
		return "!" + text + ".isEmpty"
	case protoreflect.BytesKind:
		return text + ".size != 0"
	case protoreflect.BoolKind:
		return text
	case protoreflect.EnumKind:
		zero := p.f.Enum.Desc.Values().ByNumber(0)
		if zero == nil {
			return ""
		}
		return "!(" + text + " matches ." + celtolean.LeanIdent(string(zero.Name())) + ")"
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return text + " != 0.0"
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return "" // unreachable: message fields are shapeOption
	default:
		return text + " != 0"
	}
}

func enumDesc(fd *protogen.Field) protoreflect.EnumDescriptor {
	if fd.Enum != nil {
		return fd.Enum.Desc
	}
	return nil
}

func msgDesc(fd *protogen.Field) protoreflect.MessageDescriptor {
	if fd.Message != nil {
		return fd.Message.Desc
	}
	return nil
}

func wrapType(t string) string {
	if strings.ContainsRune(t, ' ') && !strings.HasPrefix(t, "{") && !strings.HasPrefix(t, "(") {
		return "(" + t + ")"
	}
	return t
}

func freshTaken(base string, taken map[string]bool) string {
	name := base
	for i := 1; taken[name]; i++ {
		name = fmt.Sprintf("%s_%d", base, i)
	}
	return name
}

func union(a, b map[string]bool) map[string]bool {
	out := map[string]bool{}
	for k := range a {
		out[k] = true
	}
	for k := range b {
		out[k] = true
	}
	return out
}
