// Package leanvalidate generates Lean 4 refinement types from protovalidate
// CEL annotations.
//
// For every message carrying (buf.validate.field).cel or
// (buf.validate.message).cel rules, it emits — alongside grpc-lean's plain
// generated type — a validated variant in a parallel `<package>.Valid`
// namespace:
//
//   - a structure whose CEL-annotated fields are Lean subtypes of the
//     grpc-lean base field types ({ x : String // x.size ≤ 100 }), whose
//     unannotated fields reuse the base types directly, and whose
//     message-level rules are dependent Prop fields over the value fields;
//   - validate : Base → Except Protovalidate.Violation Valid, deciding each
//     rule and building the refinement (with the proofs) or reporting the
//     first violation;
//   - toBase : Valid → Base, forgetting refinements.
//
// Messages without rules keep only their base type; message-typed fields of
// validated messages recursively use the validated variant when the field
// itself carries no rules.
package leanvalidate

import (
	"fmt"
	"sort"
	"strings"

	validatepb "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/petersonbill64/protovalidate-lean/celtolean"
)

// Config parameterizes generation.
type Config struct {
	// Prefix is the Lean module prefix for the generated valid modules
	// (mirrors grpc-lean's lean4_prefix; the Bazel rule stages outputs under
	// its path form).
	Prefix string
	// BasePrefix is the module prefix the grpc-lean base codegen used for the
	// same proto sources; generated files import <BasePrefix>.<proto stem>.
	BasePrefix string
	// DepModules maps proto paths generated by *other*
	// lean_protovalidate_library targets to their module prefixes, enabling
	// cross-target validated references.
	DepModules map[string]DepModule
}

// DepModule is the module-prefix pair of a cross-target dependency.
type DepModule struct {
	Base  string
	Valid string
}

// Generate emits one Lean file per file-to-generate.
func Generate(gen *protogen.Plugin, cfg Config) error {
	targets := map[string]bool{}
	for _, f := range gen.Request.GetFileToGenerate() {
		targets[f] = true
	}
	// Files whose messages may appear as validated types: this target's plus
	// cross-target dependencies generated elsewhere.
	covered := map[string]bool{}
	for p := range targets {
		covered[p] = true
	}
	for p := range cfg.DepModules {
		covered[p] = true
	}

	msgs := map[protoreflect.FullName]*msgInfo{}
	var files []*protogen.File
	for _, f := range gen.Files {
		if !covered[f.Desc.Path()] {
			continue
		}
		if f.Generate {
			if f.Desc.Syntax() != protoreflect.Proto3 {
				return fmt.Errorf("%s: protoc-gen-lean-protovalidate supports proto3 only (matching protoc-gen-lean4)", f.Desc.Path())
			}
			files = append(files, f)
		}
		var walkErr error
		for _, m := range f.Messages {
			walkMessages(m, func(m *protogen.Message) {
				mi, err := newMsgInfo(m)
				if err != nil && walkErr == nil {
					walkErr = fmt.Errorf("message %s: %w", m.Desc.FullName(), err)
				}
				msgs[m.Desc.FullName()] = mi
			})
		}
		if walkErr != nil {
			return fmt.Errorf("%s: %w", f.Desc.Path(), walkErr)
		}
	}

	resolveNeedsValid(msgs, covered)
	if err := checkNoValidCycles(msgs, covered); err != nil {
		return err
	}

	for _, f := range files {
		if err := generateFile(gen, f, cfg, msgs, targets, covered); err != nil {
			return fmt.Errorf("%s: %w", f.Desc.Path(), err)
		}
	}
	return nil
}

type msgInfo struct {
	msg        *protogen.Message
	msgRules   []*validatepb.Rule
	fieldRules map[string]fieldRuleSet // by proto field name (lowered)
	hasOwn     bool                    // has any rule of its own (fields or message level)
	needsValid bool                    // hasOwn, or transitively contains a needsValid message field
}

func newMsgInfo(m *protogen.Message) (*msgInfo, error) {
	mi := &msgInfo{msg: m, fieldRules: map[string]fieldRuleSet{}}
	if opts, ok := m.Desc.Options().(*descriptorpb.MessageOptions); ok && opts != nil {
		if mr, ok := proto.GetExtension(opts, validatepb.E_Message).(*validatepb.MessageRules); ok && mr != nil {
			mi.msgRules = withBareExpressions(mr.GetCel(), mr.GetCelExpression())
		}
	}
	if len(mi.msgRules) > 0 {
		mi.hasOwn = true
	}
	for _, fd := range m.Fields {
		set, err := lowerFieldRules(fd)
		if err != nil {
			return mi, fmt.Errorf("field %s: %w", fd.Desc.Name(), err)
		}
		mi.fieldRules[string(fd.Desc.Name())] = set
		if !set.empty() {
			mi.hasOwn = true
		}
	}
	for _, o := range m.Oneofs {
		if !o.Desc.IsSynthetic() && oneofRequired(o) {
			mi.hasOwn = true
		}
	}
	return mi, nil
}

// oneofRequired reads (buf.validate.oneof).required.
func oneofRequired(o *protogen.Oneof) bool {
	opts, ok := o.Desc.Options().(*descriptorpb.OneofOptions)
	if !ok || opts == nil {
		return false
	}
	or, ok := proto.GetExtension(opts, validatepb.E_Oneof).(*validatepb.OneofRules)
	return ok && or.GetRequired()
}

// withBareExpressions appends the `cel_expression` string shorthand (rules
// with no id/message) to the structured `cel` rules.
func withBareExpressions(rules []*validatepb.Rule, bare []string) []*validatepb.Rule {
	out := rules
	for _, e := range bare {
		out = append(out, validatepb.Rule_builder{Expression: proto.String(e)}.Build())
	}
	return out
}

func walkMessages(m *protogen.Message, visit func(*protogen.Message)) {
	if m.Desc.IsMapEntry() {
		return
	}
	visit(m)
	for _, n := range m.Messages {
		walkMessages(n, visit)
	}
}

// validFieldEdge reports the message whose *validated* variant another
// message's validated variant embeds through fd:
//
//   - unannotated singular message fields (including oneof members, whose
//     validated sum constructors carry the validated payload) → Valid.M;
//   - repeated message fields → Array Valid.M, whether or not the field has
//     its own rules (list rules are structural — size(), unique() — so they
//     refine the array of validated elements);
//   - map values keep base types, and singular message fields with their own
//     rules refine the *base* message (their CEL inspects base fields).
func validFieldEdge(mi *msgInfo, fd *protogen.Field, msgs map[protoreflect.FullName]*msgInfo, targets map[string]bool) *msgInfo {
	if fd.Desc.IsMap() || fd.Message == nil {
		return nil
	}
	if !fd.Desc.IsList() && len(mi.fieldRules[string(fd.Desc.Name())].rules) > 0 {
		return nil
	}
	dep := msgs[fd.Message.Desc.FullName()]
	if dep == nil || !targets[fd.Message.Desc.ParentFile().Path()] {
		return nil
	}
	return dep
}

func resolveNeedsValid(msgs map[protoreflect.FullName]*msgInfo, targets map[string]bool) {
	for _, mi := range msgs {
		mi.needsValid = mi.hasOwn
	}
	for changed := true; changed; {
		changed = false
		for _, mi := range msgs {
			if mi.needsValid {
				continue
			}
			for _, fd := range mi.msg.Fields {
				if dep := validFieldEdge(mi, fd, msgs, targets); dep != nil && dep.needsValid {
					mi.needsValid = true
					changed = true
					break
				}
			}
		}
	}
}

// checkNoValidCycles rejects recursive validated structures: Lean structures
// cannot be recursive, so a needsValid message reachable from itself through
// validated message fields cannot be generated.
func checkNoValidCycles(msgs map[protoreflect.FullName]*msgInfo, targets map[string]bool) error {
	const (
		white = 0
		gray  = 1
		black = 2
	)
	state := map[protoreflect.FullName]int{}
	var visit func(mi *msgInfo, path []string) error
	visit = func(mi *msgInfo, path []string) error {
		name := mi.msg.Desc.FullName()
		switch state[name] {
		case gray:
			return fmt.Errorf("recursive message %s cannot get a validated variant (cycle: %s); "+
				"remove the CEL rules on the cycle or break it", name, strings.Join(append(path, string(name)), " -> "))
		case black:
			return nil
		}
		state[name] = gray
		for _, fd := range mi.msg.Fields {
			if dep := validFieldEdge(mi, fd, msgs, targets); dep != nil && dep.needsValid {
				if err := visit(dep, append(path, string(name))); err != nil {
					return err
				}
			}
		}
		state[name] = black
		return nil
	}
	names := sortedNames(msgs)
	for _, n := range names {
		if mi := msgs[n]; mi.needsValid {
			if err := visit(mi, nil); err != nil {
				return err
			}
		}
	}
	return nil
}

func sortedNames(msgs map[protoreflect.FullName]*msgInfo) []protoreflect.FullName {
	names := make([]protoreflect.FullName, 0, len(msgs))
	for n := range msgs {
		names = append(names, n)
	}
	sort.Slice(names, func(i, j int) bool { return names[i] < names[j] })
	return names
}

// ---------------------------------------------------------------------------
// Naming helpers

func protoStem(path string) string {
	base := path
	if i := strings.LastIndexByte(base, '/'); i >= 0 {
		base = base[i+1:]
	}
	return strings.TrimSuffix(base, ".proto")
}

// qualifyParts renders a dotted proto name as a Lean identifier path,
// quoting components that collide with Lean keywords.
func qualifyParts(name string) string {
	parts := strings.Split(name, ".")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if p != "" {
			out = append(out, celtolean.LeanIdent(p))
		}
	}
	return strings.Join(out, ".")
}

// baseQualified is the absolute Lean name of a grpc-lean generated type.
func baseQualified(name protoreflect.FullName) string {
	return "_root_." + qualifyParts(string(name))
}

// validNamespace is the namespace holding validated variants for a package.
func validNamespace(pkg protoreflect.FullName) string {
	if pkg == "" {
		return "Valid"
	}
	return qualifyParts(string(pkg)) + ".Valid"
}

// validQualified is the absolute Lean name of a message's validated variant.
func validQualified(m *protogen.Message) string {
	pkg := m.Desc.ParentFile().Package()
	local := strings.TrimPrefix(string(m.Desc.FullName()), string(pkg)+".")
	if pkg == "" {
		local = string(m.Desc.FullName())
	}
	return "_root_." + validNamespace(pkg) + "." + qualifyParts(local)
}

// localName is a message's declaration name inside its package's Valid
// namespace (nested messages keep their dotted path).
func localName(m *protogen.Message) string {
	pkg := m.Desc.ParentFile().Package()
	local := string(m.Desc.FullName())
	if pkg != "" {
		local = strings.TrimPrefix(local, string(pkg)+".")
	}
	return qualifyParts(local)
}

var scalarLean = map[protoreflect.Kind]string{
	protoreflect.BoolKind:     "Bool",
	protoreflect.Int32Kind:    "Int32",
	protoreflect.Sint32Kind:   "Int32",
	protoreflect.Sfixed32Kind: "Int32",
	protoreflect.Int64Kind:    "Int64",
	protoreflect.Sint64Kind:   "Int64",
	protoreflect.Sfixed64Kind: "Int64",
	protoreflect.Uint32Kind:   "UInt32",
	protoreflect.Fixed32Kind:  "UInt32",
	protoreflect.Uint64Kind:   "UInt64",
	protoreflect.Fixed64Kind:  "UInt64",
	protoreflect.FloatKind:    "Float32",
	protoreflect.DoubleKind:   "Float",
	protoreflect.StringKind:   "String",
	protoreflect.BytesKind:    "ByteArray",
}

func scalarText(kind protoreflect.Kind, enum protoreflect.EnumDescriptor, msg protoreflect.MessageDescriptor) (string, error) {
	if s, ok := scalarLean[kind]; ok {
		return s, nil
	}
	switch kind {
	case protoreflect.EnumKind:
		return baseQualified(enum.FullName()), nil
	case protoreflect.MessageKind:
		return baseQualified(msg.FullName()), nil
	}
	return "", fmt.Errorf("unsupported field kind %v", kind)
}

func uniqueName(base string, taken map[string]bool) string {
	name := base
	for i := 1; taken[name]; i++ {
		name = fmt.Sprintf("%s_%d", base, i)
	}
	taken[name] = true
	return name
}

// sanitizeRuleID turns a CEL rule id into a Lean-friendly identifier stem.
func sanitizeRuleID(id string, ordinal int) string {
	var b strings.Builder
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	s := b.String()
	if s == "" {
		return fmt.Sprintf("rule_%d", ordinal)
	}
	if s[0] >= '0' && s[0] <= '9' {
		s = "rule_" + s
	}
	return s
}

func docText(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.ReplaceAll(s, "-/", "- /")
}
