load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "protoc-gen-lean-protovalidate_lib",
    srcs = ["main.go"],
    importpath = "github.com/petersonbill64/protovalidate-lean/cmd/protoc-gen-lean-protovalidate",
    visibility = ["//visibility:private"],
    deps = [
        "//leanvalidate",
        "@org_golang_google_protobuf//compiler/protogen",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/pluginpb",
    ],
)

go_binary(
    name = "protoc-gen-lean-protovalidate",
    embed = [":protoc-gen-lean-protovalidate_lib"],
    visibility = ["//visibility:public"],
)
